### ISSUE TITLE
Python mismatch causes latest dds_cli executable to crash on Ubuntu Linux

### ISSUE THREAD

**Issue by nylander** [ScilifelabDataCentre/dds_cli#600] opened 2023-01-30 16:19 UTC
Latest executable for Ubuntu Linux (dds_cli v2.2.5) generates a python-related error:

```
$ ./dds --version
[449478] Error loading Python lib '/tmp/_MEIl3sj2v/libpython3.9.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /tmp/_MEIl3sj2v/libpython3.9.so.1.0)
```

Reason seems to be that some python library included(?) in the executable requires a specific version of libc (basically requiring python version 3.9), but the system has python 3.8 (and libc 2.3.1).

As far as I can see, the minimum python requirement for the executable is not documented in the [README.md](https://github.com/ScilifelabDataCentre/dds_cli#readme).

* Python versions on the server:

```
$ python -V
Python 2.7.18
$ python3 -V
Python 3.8.10
```
* OS: Ubuntu 20.04.5 LTS

* Libc version: 2.3.1

**Comment by i-oden** [comment] 2023-02-01 08:06
Aha ok! Thanks, we'll have a look.

**Comment by i-oden** [comment] 2023-02-01 13:00
Hi again, have had a look now and unfortunately I cannot reproduce this. The executables are not suppose to have a specific python requirement, that should be built in. I have created a venv with Python 3.8 and downloaded v2.2.6 and v2.2.5, and both of them work. 

Just checking something - did you rename the executable to `./dds`?

**Comment by nylander** [comment] 2023-02-01 15:08
Dear @i-oden ,

Yes, I did rename <https://github.com/ScilifelabDataCentre/dds_cli/releases/download/v2.2.6/dds_cli_ubuntu_x86_64> to `dds`.

I took the time to try all previous ubuntu x86_64 executables and the code causing the error on the server was introduced at some point between v2.2.3 and v2.2.4. That is, versions prior to v2.2.3 works, but version 2.2.4 and after generates the same error message:

```
[575271] Error loading Python lib '/tmp/_MEI1oLUlo/libpython3.9.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /tmp/_MEI1oLUlo/libpython3.9.so.1.0)
```
I couldn't find a description in the repository on how you build the executables, so I don't know where to start looking for clues. `pyinstall` may be one candidate, however.

My colleagues could download their data with the older versions, but I just thought I would give you a heads up in case someone else is sitting on an older server (without the sudo power to upgrade)...

Cheers
Johan

**Comment by i-oden** [comment] 2023-02-01 15:17
Thanks for looking into this! 

The executables are generated in this action, here: https://github.com/ScilifelabDataCentre/dds_cli/blob/d769da3db1aa3a9edc8dde176c650e27f784079a/.github/workflows/release-cli.yml#L52 

Yes, thanks for the heads up!

**Comment by nylander** [comment] 2023-02-01 15:46
Just to dig deeper into the pyinstaller issue: the "one-file" executable built by pyinstaller will create an unpack files in a temporary directory (named "_MEI<random sstring>"), and then load necessary additional files from the file system. This will pose problems if using objects with dynamic dependencies. The installation procedure for dds specifies the explicit use of python 3.9, and apparently, this generates the error we saw.
I don't know how to work around this with pyinstaller, unless there is a way of statically build all of the dependencies of the bundle/executable. An alternative may be to tell users to use a minimum required python version (and perhaps all other versions that dds may be dependent on).
/Johan

**Comment by talavis** [comment] 2023-02-03 12:55
Just making a note here: the issue is the change of `ubuntu-latest` from `ubuntu-20.04` to `ubuntu-22.04` in the Github Actions workflows.

Adding another binary for ubuntu-20.04 in the matrix should solve it.

**Comment by i-oden** [comment] 2023-02-03 12:59
Fixing as we speak. Will post here when there's an executable for 20.04 to try.

**Comment by i-oden** [comment] 2023-02-10 13:44
@nylander There's a new executable now, for Ubuntu 20.04: https://github.com/ScilifelabDataCentre/dds_cli/releases/tag/v2.2.62 
Try it out and let us know if it works now? 🙏🏻

**Comment by i-oden** [comment] 2023-02-13 12:10
Going to close this now as solved, but let us know if this is not the case! Thanks for reporting the issue

**Closed by i-oden** 2023-02-13 12:10 UTC
